# Environment overrides config.json; native authentication/configuration stays native.
set -uo pipefail
CEREBRO_HOME="${CEREBRO_HOME:-$HOME/.cerebro}"

CEREBRO_CFG_BACKEND=""
CEREBRO_CFG_MODEL=""
CEREBRO_CFG_SUPERVISOR_MODEL=""
CEREBRO_CFG_REVIEW_MODEL=""
CEREBRO_CFG_SUPERVISOR_EFFORT=""
CEREBRO_CFG_IMPLEMENTOR_EFFORT=""
CEREBRO_CFG_REVIEW_EFFORT=""
CEREBRO_CFG_TIMEOUT=""
CEREBRO_CFG_CHILD_IDLE_TIMEOUT=""
CEREBRO_CFG_PI_CMD=""
CEREBRO_CFG_CLAUDE_CMD=""
CEREBRO_CFG_CODEX_CMD=""
CEREBRO_CFG_DEBUG=""
CEREBRO_CFG_CLAUDE_BASE_URL=""
CEREBRO_CFG_CLAUDE_AUTH_TOKEN=""
CEREBRO_CFG_CHILD_SESSION_TTL=""
CEREBRO_CFG_PAIR_IDLE=""
CEREBRO_CFG_PAIR_STALL=""
CEREBRO_CFG_PAIR_STALL_BUSY=""
CEREBRO_CFG_JEV_ENABLED=""
CEREBRO_CFG_JEV_API_KEY=""
CEREBRO_CFG_JEV_MODEL=""
CEREBRO_CFG_JEV_ENDPOINT=""
CEREBRO_CFG_JEV_CONFIDENCE=""
_cerebro_options_load() {
  local cfg="$CEREBRO_HOME/config.json" k v
  [[ -r "$cfg" && -s "$cfg" ]] || return 0
  while IFS=$'\t' read -r k v; do
    case "$k" in
      backend) CEREBRO_CFG_BACKEND="$v" ;;
      model) CEREBRO_CFG_MODEL="$v" ;;
      supervisor_model) CEREBRO_CFG_SUPERVISOR_MODEL="$v" ;;
      review_model) CEREBRO_CFG_REVIEW_MODEL="$v" ;;
      supervisor_effort) CEREBRO_CFG_SUPERVISOR_EFFORT="$v" ;;
      implementor_effort) CEREBRO_CFG_IMPLEMENTOR_EFFORT="$v" ;;
      review_effort) CEREBRO_CFG_REVIEW_EFFORT="$v" ;;
      timeout) CEREBRO_CFG_TIMEOUT="$v" ;;
      child_idle_timeout) CEREBRO_CFG_CHILD_IDLE_TIMEOUT="$v" ;;
      pi_cmd) CEREBRO_CFG_PI_CMD="$v" ;;
      claude_cmd) CEREBRO_CFG_CLAUDE_CMD="$v" ;;
      codex_cmd) CEREBRO_CFG_CODEX_CMD="$v" ;;
      debug) CEREBRO_CFG_DEBUG="$v" ;;
      claude_base_url) CEREBRO_CFG_CLAUDE_BASE_URL="$v" ;;
      claude_auth_token) CEREBRO_CFG_CLAUDE_AUTH_TOKEN="$v" ;;
      child_session_ttl) CEREBRO_CFG_CHILD_SESSION_TTL="$v" ;;
      pair_idle) CEREBRO_CFG_PAIR_IDLE="$v" ;;
      pair_stall) CEREBRO_CFG_PAIR_STALL="$v" ;;
      pair_stall_busy) CEREBRO_CFG_PAIR_STALL_BUSY="$v" ;;
      jev_enabled) CEREBRO_CFG_JEV_ENABLED="$v" ;;
      jev_api_key) CEREBRO_CFG_JEV_API_KEY="$v" ;;
      jev_model) CEREBRO_CFG_JEV_MODEL="$v" ;;
      jev_endpoint) CEREBRO_CFG_JEV_ENDPOINT="$v" ;;
      jev_confidence) CEREBRO_CFG_JEV_CONFIDENCE="$v" ;;
    esac
  done < <(jq -r 'to_entries[] | "\(.key)\t\(.value|tostring)"' "$cfg")
}
_cerebro_options_load

CEREBRO_BACKEND="${CEREBRO_BACKEND:-${CEREBRO_CFG_BACKEND:-pi}}"
CEREBRO_MODEL="${CEREBRO_MODEL-${CEREBRO_CFG_MODEL:-}}"
CEREBRO_SUPERVISOR_MODEL="${CEREBRO_SUPERVISOR_MODEL-${CEREBRO_CFG_SUPERVISOR_MODEL:-}}"
CEREBRO_REVIEW_MODEL="${CEREBRO_REVIEW_MODEL-${CEREBRO_CFG_REVIEW_MODEL:-}}"
CEREBRO_SUPERVISOR_EFFORT="${CEREBRO_SUPERVISOR_EFFORT-${CEREBRO_CFG_SUPERVISOR_EFFORT:-}}"
CEREBRO_IMPLEMENTOR_EFFORT="${CEREBRO_IMPLEMENTOR_EFFORT-${CEREBRO_CFG_IMPLEMENTOR_EFFORT:-}}"
CEREBRO_REVIEW_EFFORT="${CEREBRO_REVIEW_EFFORT-${CEREBRO_CFG_REVIEW_EFFORT:-}}"
CEREBRO_TIMEOUT="${CEREBRO_TIMEOUT:-${CEREBRO_CFG_TIMEOUT:-0}}"
CEREBRO_CHILD_IDLE_TIMEOUT="${CEREBRO_CHILD_IDLE_TIMEOUT:-${CEREBRO_CFG_CHILD_IDLE_TIMEOUT:-0}}"
CEREBRO_PI_CMD="${CEREBRO_PI_CMD:-${CEREBRO_CFG_PI_CMD:-pi}}"
CEREBRO_CLAUDE_CMD="${CEREBRO_CLAUDE_CMD:-${CEREBRO_CFG_CLAUDE_CMD:-claude}}"
CEREBRO_CODEX_CMD="${CEREBRO_CODEX_CMD:-${CEREBRO_CFG_CODEX_CMD:-codex}}"
CEREBRO_DEBUG="${CEREBRO_DEBUG:-${CEREBRO_CFG_DEBUG:-0}}"
CEREBRO_CLAUDE_BASE_URL="${CEREBRO_CLAUDE_BASE_URL:-${CEREBRO_CFG_CLAUDE_BASE_URL:-}}"
CEREBRO_CLAUDE_AUTH_TOKEN="${CEREBRO_CLAUDE_AUTH_TOKEN:-${CEREBRO_CFG_CLAUDE_AUTH_TOKEN:-}}"
CEREBRO_CHILD_SESSION_TTL="${CEREBRO_CHILD_SESSION_TTL:-${CEREBRO_CFG_CHILD_SESSION_TTL:-86400}}"
CEREBRO_PAIR_IDLE="${CEREBRO_PAIR_IDLE:-${CEREBRO_CFG_PAIR_IDLE:-0}}"
CEREBRO_PAIR_STALL="${CEREBRO_PAIR_STALL:-${CEREBRO_CFG_PAIR_STALL:-0}}"
CEREBRO_PAIR_STALL_BUSY="${CEREBRO_PAIR_STALL_BUSY:-${CEREBRO_CFG_PAIR_STALL_BUSY:-0}}"
CEREBRO_JEV_ENABLED="${CEREBRO_JEV_ENABLED:-${CEREBRO_CFG_JEV_ENABLED:-0}}"
CEREBRO_JEV_API_KEY="${CEREBRO_JEV_API_KEY:-${CEREBRO_CFG_JEV_API_KEY:-}}"
CEREBRO_JEV_MODEL="${CEREBRO_JEV_MODEL:-${CEREBRO_CFG_JEV_MODEL:-jev-latest}}"
CEREBRO_JEV_ENDPOINT="${CEREBRO_JEV_ENDPOINT:-${CEREBRO_CFG_JEV_ENDPOINT:-https://api.typesafe.ai/v1/systemone}}"
CEREBRO_JEV_CONFIDENCE="${CEREBRO_JEV_CONFIDENCE:-${CEREBRO_CFG_JEV_CONFIDENCE:-0.8}}"
